### ISSUE TITLE
Vertaisarviointi 

### ISSUE THREAD

**Issue by mikkohyy** [TopiasHarjunpaa/MaxxSoft#2]
Vertaisarvinointi versiosta, joka oli Githubissa 26.8. noin kello 10:00.

Sovellus vaikuttaa olevan aika valmis, joten palautteeni käsittelee pääasiallisesti melko pieniä asioita, kuten esimerkiksi painikkeiden sijoittamista.

Käyttökokemus

* Kokonaisuutena käyttökokemus on hyvä ja käyttöliittymiä on selkeä
* Kirjaudu ulos -painike valikon vasemmalla puolella tuntuu olevan väärässä paikassa. Kun aloitan uloskirjautumisen, lähden etsimään sitä aina oikealta puolelta. Tuntuisi, että on tavanmukaisesti uloskirjautuminen on yleensä sijoitettu valikon oikeaan laitaan nettisivuilla. Kirjaudu ulos -painikkeen sijoittuminen vasemmalle siis ikään kuin keskeyttää hyvän käyttökokemuksen häiritsevällä tavalla. 
* Kalustolistan luomisessa sääsuojan tietojen antamisen jälkeen näytettävien tietojen yhteydessä oleva "Muokkaa kalustolistaa" -painike on ehkä harhaanjohtavasti nimetty. Kun painoin sitä, odotin pääseväni muokkaamaan listaa, joka näkyy painikkeen yläpuolella. Sen sijaan päädyin takaisin sääsuojan tietojen antamiseen. "Muuta sääsuojan tietoja" tai vastaava olisi luultavasti sopivampi teksti kyseiselle painikkeelle. 
* Testaa tietosi -peli voisi vastauksen antamisen jälkeen keskittää sivuston "Testaa tietosi -peli" otsikkoon eikä sivun ylälaitaan. Koneen näyttö, jolla tein testaamisen on 13,3 tuuman näyttö, ja jouduin aina vierittämään näkymää alaspäin vastaamisen jälkeen. 

Koodi

* Koodi on selkeää ja projektin ulkopuolelta tulevan henkilön, joka näkee koodin ensimmäistä kertaa, on helppo lukea koodia ja ymmärtää mitä ja miksi mitäkin asioita tehdään. 
* Perks.py -moduulissa rivillä 23 olevassa sql-lauseessa haettavat kolumnit määritellään "SELECT * FROM"-lausekkeella ja käsittääkseni parempi käytäntö olisi määrittää selkeästi mitä kolumneja haetaan. Sama "SELECT *" oli myös product.py:ssä riveillä 51 ja 62 sekä roles.py:n rivillä 9.
* Product_list.py:ssä riviltä 11 alkava calculate_materials() funktio on melko pitkä ja sen voisi pilkkoa pienempiin. Funktiossa kommentteina olevat kuvaukset mitä mikäkin osio funktiosta tekee ovat hyvä lähtökohta siihen miten funktion voisi pilkkoa pienempiin funktioihin. 
* Routes.py:ssä oleva tjs_game -funktio (joka on selkeästi oma itsenäinen kokonaisuutensa sovelluksessa) olisi luultavasti mielekästä siirtää omaksi moduulikseen, joka olisi jaettu pienempiin funktioihin. 
* Html-koodissa esiintyy usein elementtien tyylien määrittelyä (esimerkiksi h6 style="margin-top: 10px;" toistuu aika usein) ja voisi olla kätevää tehdä nämä toistuvat määrittelyt style.css:ssä.
* Käyttäjätunnuksen pituutta voisi olla mielekästä rajoittaa. Rekisteröin käyttäjän nimellä "erwqrqweotuwqioetuwoeiqtuoiqweutoiwequtoiweutoiweuqotiuweqoituweqopituweqpoituweqoiptuweqtpoiuqweiotuweqpotuwqetoipwuopiu" ja tämä rikkoi sivun asettelun ja teki esimerkiksi "Lista käyttäjistä:" -taulukon käyttämisestä vaikeaa.

Sovellus on mielestäni kokonaisuutena hyvin tehty, koodattu ja näyttää hienolta.

**Comment by TopiasHarjunpaa** [comment]
Kiitos kommenteista. Näistä oli suuresti apua harjoitustyön loppuun saattamisessa. Lopulliseen palautettavaan versioon tein seuraavat muutokset:

- Kirjaudu ulos -painikkeen siirtäminen
- Kalustolistan muokkaaminen toimii nyt hieman loogisemmin
- SELECT * FROM komennot muutettu
- Käyttäjätunnuksen pituus on rajoitettu

Myös kaikki muut kommenttisi olivat hyviä ja olen niiden osalta samaa mieltä. Etenkin tuo sivun keskittäminen testaa tietosi -pelissä olisi erittäin hyödyllinen parannus. Nämä jäivät nyt kuitenkin harjoitustyön aikarajoissa tekemättä, mutta ehkäpä palaan vielä näihin, mikäli innostun jatkamaan sovelluksen kehittämistä myöhemmin.
